enum ACTION_TYPES {
    FETCH_USER_DATA_INIT = 'FETCH_USER_DATA_INIT',
    FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR',

    FETCH_USER_VEHICLES_INIT = 'FETCH_USER_VEHICLES_INIT',
    FETCH_USER_VEHICLES_SUCCESS = 'FETCH_USER_VEHICLES_SUCCESS',
    FETCH_USER_VEHICLES_ERROR = 'FETCH_USER_VEHICLES_ERROR',

    FETCH_VEHICLE_RECORDS_INIT = 'FETCH_VEHICLE_RECORDS_INIT',
    FETCH_VEHICLE_RECORDS_SUCCESS = 'FETCH_VEHICLE_RECORDS_SUCCESS',
    FETCH_VEHICLE_RECORDS_ERROR = 'FETCH_VEHICLE_RECORDS_ERROR',

    CREATE_USER_INIT = 'CREATE_USER_INIT',
    CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR = 'CREATE_USER_ERROR',

    DELETE_USER_INIT = 'DELETE_USER_INIT',
    DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
    DELETE_USER_ERROR = 'DELETE_USER_ERROR',

    ADD_USER_VEHICLE_INIT = 'ADD_USER_VEHICLE_INIT',
    ADD_USER_VEHICLE_SUCCESS = 'ADD_USER_VEHICLE_SUCCESS',
    ADD_USER_VEHICLE_ERROR = 'ADD_USER_VEHICLE_ERROR',

    DELETE_USER_VEHICLE_INIT = 'DELETE_USER_VEHICLE_INIT',
    DELETE_USER_VEHICLE_SUCCESS = 'DELETE_USER_VEHICLE_SUCCESS',
    DELETE_USER_VEHICLE_ERROR = 'DELETE_USER_VEHICLE_ERROR',

    ADD_VEHICLE_RECORD_INIT = 'ADD_VEHICLE_RECORD_INIT',
    ADD_VEHICLE_RECORD_SUCCESS = 'ADD_VEHICLE_RECORD_SUCCESS',
    ADD_VEHICLE_RECORD_ERROR = 'ADD_VEHICLE_RECORD_ERROR',    

    UPDATE_VEHICLE_RECORD_INIT = 'UPDATE_VEHICLE_RECORD_INIT',
    UPDATE_VEHICLE_RECORD_SUCCESS = 'UPDATE_VEHICLE_RECORD_SUCCESS',
    UPDATE_VEHICLE_RECORD_ERROR = 'UPDATE_VEHICLE_RECORD_ERROR',  
    
    DELETE_VEHICLE_RECORD_INIT = 'DELETE_VEHICLE_RECORD_INIT',
    DELETE_VEHICLE_RECORD_SUCCESS = 'DELETE_VEHICLE_RECORD_SUCCESS',
    DELETE_VEHICLE_RECORD_ERROR = 'DELETE_VEHICLE_RECORD_ERROR', 

    SELECT_USER = 'SELECT_USER',
    SELECT_VEHICLE = 'SELECT_VEHICLE',

    SET_PAGE_STATUS= 'SET_PAGE_STATUS'
}

export default ACTION_TYPES;